apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "production"
  GATEWAY_HTTP_ADDR: ":8081"
  JAEGER_ENDPOINT: "http://jaeger.default.svc.cluster.local:14268/api/traces"
  STRIPE_SUCCESS_URL: "http://35.247.179.170/payment/success?payment=success"
  STRIPE_CANCEL_URL: "http://35.247.179.170/payment/cancel?payment=cancel"
